### ISSUE TITLE
Submission Form work: First pass at event categories

### ISSUE THREAD

**Issue by MatthewGidcomb** [infinite-industries/infinite#286]
Part of the larger submission form rework:

Add "Which of these describes your event?" radio group after title. Options are:

- **Single-day event**
- **Gallery Show**
- **Multi-day event**
- **Online resource**
- **Call-for-entry**
- **Other** (please specify)

(additional descriptions to be written)

Still TBD: how do we store this information on the event? Current idea is to shove it into tags, maybe with a prefix e.g. `type:<type>` or `description:<type>`; `other` could look something like `type:other:what-they-put-in-field`.

Stretch goal: if there's a suggested tag that matches the category, automatically insert it into the tags field (e.g. `gallery`).

**Comment by Digi-D** [comment]
Copy: 
Is your event* :

Live (in-person)  Online  Hybrid

Online events occur at a particular time. Online Resources are always available (like a website or a link to a video). Hybrid events are a mixture of the two (a live concert with an online streaming component is an example.)

Which of these best describes your event* ?

Single-day event, like a music concert or a poetry reading.
Gallery Show stretching over multiple weeks; with an opening and special events.
Multi-day event, like a music festival or a conference. 
Online resource with no specific start/end date. Just a link to share info on a topic or and an idea.   
Call-for-entry with a single date/time. Invite creative peoples to submit their work. 
Other. Surprise us. What type of an event are you putting on?

![Event_Type](https://user-images.githubusercontent.com/5461265/168159980-f7b79d9f-d8ce-4fb1-8acc-38435dea8afa.png)
