### ISSUE TITLE
Add better styles to Submission Preview view

### ISSUE THREAD

**Issue by Digi-D** [infinite-industries/infinite#304]
**Implement the following on submission preview in order to minimize the cognitive load on users when submitting events** 

<img width="1156" alt="Screen Shot 2022-10-30 at 12 28 41 PM" src="https://user-images.githubusercontent.com/5461265/198890218-e8a275b0-4063-4593-8b74-97a874b145ff.png">

Primary Green -->
```
background-color: #6cba70;
font-family: "Open Sans",sans-serif;
color: #000;
border: 2px solid black;
border-radius: 3px;
margin: 8px;
padding: 10px;
font-size: 14px;
```

Secondary Grey -->
```
background-color: #d8d7d7;
border: 1px solid black;
padding: 11px;
```

**Comment by Digi-D** [comment]
Implemented on site.

**Comment by MatthewGidcomb** [comment]
PR #339
