### ISSUE TITLE
Design & rework venue address display

### ISSUE THREAD

**Issue by rlmead** [infinite-industries/infinite#319]
Currently, we don't display any event address information on the cards. We could consider displaying city and/or state somewhere prominent, and perhaps full address information somewhere less prominent.

We might also consider using map link data to display a map, sort of like @jswank does [here](https://observablehq.com/d/3a17b8a83df81b83#cell-346).

Places to consider location data redesign:
* Event card
* Event page
* Venue input
* Admin venue editing

**Comment by Digi-D** [comment]
Punting on Venue input Admin venue editing

**Comment by Digi-D** [comment]
Desktop view

![Image](https://user-images.githubusercontent.com/5461265/216833024-f283befa-cea7-4cfd-adaf-9fe22d875ba2.jpg)


Card view



![Image](https://user-images.githubusercontent.com/5461265/216833086-452d2c6c-7969-4260-b1b9-439bbaea07b8.png)
