### ISSUE TITLE
FB doesn't display images 

### ISSUE THREAD

**Issue by Digi-D** [infinite-industries/infinite#32]
When sharing events on FB, images are not shared with the rest of the event info. 

Debugger spits out the following message: 
```The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags```

Example --> https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Finfinite.industries%2Fevents%2Ffa10e5a0-fb69-11e9-b43e-456ed9f9b823

**Comment by chriswininger** [comment]
we were sending the wrong link. This is fixed and released
