### ISSUE TITLE
Get rid of redundant event location fields

### ISSUE THREAD

**Issue by rlmead** [infinite-industries/infinite#347]
The `events` table in the database includes two location-related columns:
* `address`
* `map_link`

These are redundant with corresponding fields in the `venues` table and can be removed. We should remove/change any references to the two `events` fields in the codebase, then drop them in the database.

See relevant Slack discussion [here](https://1nfinite1ndustries.slack.com/archives/C1DUR2VNW/p1673897313718519).

**Comment by MatthewGidcomb** [comment]
Looks like the `address` column is populated in the submission form when a venue is selected (see [here](https://github.com/infinite-industries/infinite/blob/d0c10c5688b97240e0186c60d022467578b592e2/web-portal/components/SubmissionForm.vue#L537-L548)). We can remove that logic from those event handlers as well as removing the properties from the DTOs on the API server (as well as the migration to remove the columns, of course). I don't see where the `map_link` is set on the event, though -- maybe that column isn't even wired up anymore.
