### ISSUE TITLE
Systematically fix bad location data

### ISSUE THREAD

**Issue by rlmead** [infinite-industries/infinite#350]
[Github gist](https://gist.github.com/jswank/ed88308b93647e5c637897a6dbd8230e)
[Observable project](https://observablehq.com/d/3a17b8a83df81b83)

**Comment by jswank** [comment]
Create two SQL files:

1. Update: lat / lon
2. Add new fields: street, city, state, zip, neighborhood

**Comment by jswank** [comment]
Lon / Lat update sql: https://gist.github.com/jswank/559c86ee490f03c8f85840e1c8ed2477

**Comment by jswank** [comment]
Geo update SQL  **with updated address field** : https://gist.githubusercontent.com/jswank/e3986c5ebe08812f9dfe2ee952251c90/raw/f8e0c7369602eeab8549ccb77b7779659e926af0/venues-geo.sql
