### ISSUE TITLE
Downsample Images

### ISSUE THREAD

**Issue by chriswininger** [infinite-industries/infinite#356]
We are currently storing event images exactly as submitted. Some our quite quite large. This makes site loading slower and costs us money. We should down sample these to some target range.

**Acceptance Criteria:**
* Consider how we down sample, do we ensure a certain file size or a certain image size
* Do we need to restrict the input a bit more to make this possible
* Do we have a super down sampled image for the thumbnails vs the event details page

Note: There is a broader question about letting users resize and crop images to fit our format, but for the purposes of this ticket that is not required. Think more about an easy win to prevent 13 MB images getting onto the home page

**Comment by MatthewGidcomb** [comment]
[Here](https://github.com/infinite-industries/infinite/blob/development/web-portal/internal-api/upload-images.js#L46-L97)'s where image uploads are handled. This request handler delegates to a separate uploader class (implementations [here](https://github.com/infinite-industries/infinite/tree/development/web-portal/internal-api/upload-managers)); the specific implementation is chosen at server start based on what's set in the environment.
