### ISSUE TITLE
Investigate Google Analytics alternatives

### ISSUE THREAD

**Issue by MatthewGidcomb** [infinite-industries/infinite#372]
The setup we're using will stop working in June 2023, and since we've long discussed moving to something less creepy, this seems like a good time.

First we need to choose an alternative. There are plenty out there. The leading candidate is probably [Fathom](https://usefathom.com/), because Jason has experience with it. I've run across three others over time that I've made notes of as possible contenders, as well: [Ackee](https://ackee.electerious.com/), [Plausible](https://plausible.io/), and [Umami](https://umami.is/).

This issue is just about making the decision on which alternative we will move forward with.

**Comment by MatthewGidcomb** [comment]
Much more analysis needs to be done, but as an overview:

| Option    |Hosting      | Open Source                                    | Maintained                 | Public Demo Page                                                   | Other                                                                                                                          |
|-----------|-------------|------------------------------------------------|----------------------------|--------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------|
| Fathom    | Hosted*     | Not really*                                    | Presumably                 | [Yes](https://app.usefathom.com/share/deasaicp/hilarious+platypus) | [Vue plugin (old)](https://github.com/ubclaunchpad/vue-fathom), [Nuxt plugin (also old)](https://github.com/yabhq/nuxt-fathom) |
| Ackee     | Self-hosted | [Yes](https://github.com/electerious/Ackee)    | Yes; last release Dec 2022 | [Yes](https://demo.ackee.electerious.com/), but requires login?    | [Nuxt plugin](https://github.com/nuxt-community/ackee-module)                                                                  |
| Plausible | Both        | [Yes](https://github.com/plausible/analytics)  | Yes; last release Dec 2022 | [Yes](https://plausible.io/plausible.io)                           | [Vue plugin](https://github.com/moritzsternemann/vue-plausible)                                                                |
| Umami     | Self-hosted | [Yes](https://github.com/umami-software/umami) | Yes; last release Jan 2023 | [Yes](https://app.umami.is/share/8rmHaheU/umami.is)                | [Nuxt plugin](https://github.com/ijkml/nuxt-umami)                                                                             |

\* There's an older version of the project that's available on [Github](https://github.com/usefathom/fathom), but not maintained.

I haven't given any of the Nuxt/Vue plugins more than a cursory glance. It might be worth either investigating a more general analytics plugin that supports plugging in various providers, or rolling our own using one of these as a reference.

**Comment by MatthewGidcomb** [comment]
The plan now is to try Fathom as soon as possible, ideally running both it and GA3 for at least a week to be sure we're happy with it. That puts a limit on how long we have to do this -- I believe we have until July 5th with GA3, not sure how bad it may be if prod is still trying to use it after the backend shuts off.

Per [this article](https://usefathom.com/docs/integrations/nuxt) Dima found, the Fathom Vue plugin linked above is recommended by Fathom, although it's not their official plugin and it hasn't been updated in a while. It's also for Vue 3, but maybe we could use an older version for Vue 2 until we take on that upgrade. Alternatively, it's only 25 lines of code and whitespace, so we could just copy what it's doing (and possibly simplify, it's doing some things that I think are to support TypeScript).

**Comment by MatthewGidcomb** [comment]
Fathom is now in production (see #412, #416, and #417). Will remove GA next week unless we encounter a problem.

**Comment by Blaumaus** [comment]
@MatthewGidcomb feel free also to take a look at [Swetrix](https://swetrix.com), I'm actively building this project.
Here's a table to easily compare it with others:

Option | Hosting | Open Source | Maintained | Public Demo Page | Other
-- | -- | -- | -- | -- | --
Swetrix | Both | [Yes](https://github.com/swetrix) | Yes | [Yes](https://swetrix.com/projects/STEzHcB1rALV?tab=traffic) | [Vue plugin](https://github.com/ansidev/swetrix-vue)*

*As for NuxtJS - we support server-side tracking or you can simply use `swetrix` package which works in all SPAs.
