### ISSUE TITLE
All the images are uploaded as a JPEG regardless of the actual file type

### ISSUE THREAD

**Issue by Digi-D** [infinite-industries/infinite#436]
Currently, all of the images are uploaded with .jpg suffix regardless of their actual file type. 

Doesn't break since the S3 bucket returns it as "application/octet-stream" MIME type but needs to be changed to the appropriate suffix or avoid suffixes all together.

**Comment by MatthewGidcomb** [comment]
Cause of hard-coded `.jpg` suffix:

https://github.com/infinite-industries/infinite/blob/5f3033c1292ff6483d432796a074610c0c7a2287/web-portal/internal-api/upload-images.js#L13-L18

**Comment by MatthewGidcomb** [comment]
Fixed by #454
