### ISSUE TITLE
Speed up image loading on home screen

### ISSUE THREAD

**Issue by chriswininger** [infinite-industries/infinite#46]
On a slow connection all our images on the home page can take a while to dl, additionally while this is happening the hamburger menu doesn't seem to work correctly. Perhaps there is a way to let the page be more interactive while this is happening. Additionally the images on this page are displayed very small, perhaps when the images are uploaded we can generate a re-scaled thumbnail version for use when showing in a list

**Comment by MatthewGidcomb** [comment]
See #356
