### ISSUE TITLE
Upgrade to Node 18/20

### ISSUE THREAD

**Issue by MatthewGidcomb** [infinite-industries/infinite#470]
Node terminated v16, which we use, early due to the EOL of OpenSSL 1.1.1 (see [here](https://nodejs.org/en/blog/announcements/nodejs16-eol)). We should investigate upgrading.

I don't think it'll be any more involved than bumping the version in the `.nvmrc` file, but might need to check the new build stack.

**Comment by chriswininger** [comment]
upgraded to 20 for everything but the widget which is mostly abandoned until there is interest
