### ISSUE TITLE
Uploading event on Safari doesn't work 

### ISSUE THREAD

**Issue by Digi-D** [infinite-industries/infinite#63]
Get "Hmmm... something went wrong :("

Kicks out --> 

[Error] Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers. (events, line 0)
[Error] XMLHttpRequest cannot load https://api.infinite.industries/events. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
[Log] Error: Network Error (f1fc998f3ede5df3d68f.js, line 1)

**Comment by chriswininger** [comment]
Interesting, any additional repo steps. I just tested submission on Safari against staging and prod and it all seemed to work. Is this perhaps fixed now?

**Comment by Digi-D** [comment]
Observed on Mac 10.13.2 Safari Version 11.0.2 (13604.4.7.1.3)

Uploading: -------- :
{"id":"","title":"Testing 9am to 5pm -- what a way to make a living","date_times":[{"optional_title":"","start_time":"2019-12-13 09:00 EST","end_time":"2019-12-13 17:00 EST"}],"image":"","social_image":"","organizers":"","admission_fee":"none","venue":{"name":"","id":"","slug":"","createdAt":"","updatedAt":"","g_map_link":"","address":""},"address":"193 N Limestone, Lexington, KY 40507","brief_description":"asdfasdf","description":"<p>testing more</p>","website_link":"","eventbrite_link":"","fb_event_link":"","ticket_link":"","organizer_contact":"dima@di.ma","multi_day":false,"additional_dates":[],"venue_id":"d0858cc0-0478-11e8-808e-07b6d0fe568b","venue_name":"Institute 193"}


[Error] Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers. (events, line 0)

XMLHttpRequest cannot load https://api.infinite.industries/events. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

**Comment by chriswininger** [comment]
my safari version is newer; so, that's likely why I don't see this, but we should still fix it as I'm sure many people are not current. I have an old laptop I don't update as much I'll try testing on that one too

**Comment by chriswininger** [comment]
fixed with 7a7f51c983ca1b5f316615245bd29e2a39e7172e
